defaults:
  - _self_
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

seed: 42

datamodule:
  _target_: data.GaussianDataModule
  prior_stdev: 5.0
  likelihood_stdev: 1.0
  num_observations: 100
  num_batches: 100
  batch_size: 256
  train_split: 0.8
  val_split: 0.1

# primal, DRNPE
encoder:
  _target_: encoder.Encoder
  objective: "primal"
  kl_ball_threshold: 0.0  # irrelevant if objective is "primal"
  initial_lambda: 0.1
  x_dim: ${datamodule.num_observations}
  num_hidden_channels: 64
  lr: 1e-4

# primal, standard NPE
# encoder:
#   _target_: encoder.Encoder
#   objective: "primal"
#   kl_ball_threshold: 0.0  # irrelevant if objective is "primal"
#   initial_lambda: 1000000.0
#   x_dim: ${datamodule.num_observations}
#   num_hidden_channels: 64
#   lr: 1e-4

# dual, DRNPE
# encoder:
#   _target_: encoder.Encoder
#   objective: "dual"
#   kl_ball_threshold: 2.0
#   initial_lambda: 1.0
#   x_dim: ${datamodule.num_observations}
#   num_hidden_channels: 64
#   lr: 1e-4

# dual, standard NPE
# encoder:
#   _target_: encoder.Encoder
#   objective: "dual"
#   kl_ball_threshold: 0.0
#   initial_lambda: 1.0
#   x_dim: ${datamodule.num_observations}
#   num_hidden_channels: 64
#   lr: 1e-4

trainer:
  _target_: lightning.Trainer
  max_epochs: 1000
  accelerator: gpu
  devices: 1
  logger:
    _target_: lightning.pytorch.loggers.TensorBoardLogger
    save_dir: logs
    name: drnpe_${encoder.objective}_kl${encoder.kl_ball_threshold}_lambda${encoder.initial_lambda}
    version: ""
  callbacks:
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val_loss
      patience: 50
      mode: min
      verbose: true
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      monitor: val_loss
      mode: min
      save_top_k: 1
      filename: "network_epoch{epoch}"
      auto_insert_metric_name: false
      verbose: true
